"""add user team pull request and pr reviewer tables

Revision ID: 9514d0d4a099
Revises:
Create Date: 2025-11-16 14:56:14.174274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9514d0d4a099"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("team_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("team_name"),
    )
    op.create_index(op.f("ix_teams_team_name"), "teams", ["team_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("team_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_name"], ["teams.team_name"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_team_name"), "users", ["team_name"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("pull_request_id", sa.String(length=255), nullable=False),
        sa.Column("pull_request_name", sa.String(length=500), nullable=False),
        sa.Column("author_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "MERGED", name="prstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("merged_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.user_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("pull_request_id"),
    )
    op.create_index(
        op.f("ix_pull_requests_author_id"), "pull_requests", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_pull_requests_pull_request_id"),
        "pull_requests",
        ["pull_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pull_requests_status"), "pull_requests", ["status"], unique=False
    )
    op.create_table(
        "pr_reviewers",
        sa.Column("pull_request_id", sa.String(length=255), nullable=False),
        sa.Column("reviewer_id", sa.String(length=255), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.pull_request_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.user_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("pull_request_id", "reviewer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pr_reviewers")
    op.drop_index(op.f("ix_pull_requests_status"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_pull_request_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_author_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_team_name"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_teams_team_name"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
